"""Compose/install sitting-owned slots after a clean probe sweep; never while Mars runs."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
KIT = ROOT.parent / 'SMR-BugFixPack-TestKit'
HERE = Path(__file__).resolve().parent
p = argparse.ArgumentParser()
p.add_argument('--install', action='store_true')
args = p.parse_args()
run = subprocess.run(['C:/Program Files/Git/usr/bin/grep.exe', '-rln', 'TEMPORARY',
                      'Code/', '../SMR-BugFixPack-TestKit/Code/'], cwd=ROOT, capture_output=True, text=True)
if run.returncode != 1 or run.stdout or run.stderr:
    raise SystemExit('Probe sweep not clean: ' + run.stdout + run.stderr)
evidence = dict(command='grep -rln "TEMPORARY" Code/ ../SMR-BugFixPack-TestKit/Code/', output='',
                pack_head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
                testkit_head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=KIT,text=True).strip(),
                checked_at=datetime.now(timezone.utc).isoformat(), brief='Arboretum D19 attended sitting')
lines = ['T.PreloadProbeSweep {\n']
for k,v in evidence.items():
    lines.append('\t' + k + ' = ' + json.dumps(v).replace('TEMPORARY','TEMP" .. "ORARY') + ',\n')
lines.append('\texit = 1, hits = {}, needed = {},\n}\n')
source = (HERE / 'slots.lua.txt').read_text(encoding='utf-8')
if source.count('-- @@PROBE_SWEEP@@\n') != 1:
    raise SystemExit('Missing/duplicate sweep marker')
body = ('-- GENERATED by Opt-In tools/arboretum/preload.py from slots.lua.txt.\n'
        + source.replace('-- @@PROBE_SWEEP@@\n', ''.join(lines))).encode('utf-8')
(HERE / '80_AgentSlots.lua.txt').write_bytes(body)
if args.install:
    tasks = subprocess.check_output(['tasklist','/FI','IMAGENAME eq Mars.exe','/FO','CSV'],text=True)
    if '"Mars.exe"' in tasks:
        raise SystemExit('Mars.exe is running; not installing slots')
    (KIT / 'Code/80_AgentSlots.lua').write_bytes(body)
    if (KIT / 'Code/80_AgentSlots.lua').read_bytes() != body:
        raise SystemExit('Installed readback differs')
evidence.update(installed=args.install, sha256=hashlib.sha256(body).hexdigest())
(HERE / 'preload_receipt.json').write_text(json.dumps(evidence,indent=2)+'\n',encoding='utf-8',newline='\n')
print(json.dumps(evidence,indent=2))
