"""Compose (and optionally install) the pre-launch train SOAK sitting slots.

Source:  soak_slots.lua.txt beside this script (edit it, never the output).
Output:  80_AgentSlots_soak.lua.txt + preload_receipt.json beside this script.
Install: --install copies the output to the TestKit's Code/80_AgentSlots.lua, only while
         Mars.exe is not running, and records the installed hash in the receipt.

The probe sweep (docs/agent/WORKFLOW.md "Probe hygiene") runs here, from this repo's root,
with the exact command SMRTK's preflight expects; its live output, exit code, both HEADs and
the time go into SMRTK.PreloadProbeSweep at the top of the slots (tools/SMRTK.md).

    python tools/trains/soak/compose.py            # compose only
    python tools/trains/soak/compose.py --install  # compose, then install (game closed)
"""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil
import subprocess

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
KIT = ROOT.parent / "SMR-BugFixPack-TestKit"
SOURCE = HERE / "soak_slots.lua.txt"
OUTPUT = HERE / "80_AgentSlots_soak.lua.txt"
RECEIPT = HERE / "preload_receipt.json"
TARGET = KIT / "Code" / "80_AgentSlots.lua"
GREP = "C:/Program Files/Git/usr/bin/grep.exe"
SWEEP = 'grep -rln "TEMPORARY" Code/ ../SMR-BugFixPack-TestKit/Code/'
MARKER = "-- @@PROBE_SWEEP@@\n"


def head(repo):
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()


def sweep():
    word = "TEMP" + "ORARY"
    run = subprocess.run([GREP, "-rln", word, "Code/", "../SMR-BugFixPack-TestKit/Code/"],
                         cwd=ROOT, capture_output=True, text=True)
    hits = [line for line in run.stdout.splitlines() if line.strip()]
    return {"command": SWEEP, "executable": GREP, "output": run.stdout, "exit": run.returncode,
            "hits": hits, "pack_head": head(ROOT), "testkit_head": head(KIT),
            "checked_at": datetime.now(timezone.utc).isoformat(),
            "brief": "pre-launch train soak (2026-10-03): read-only stream, no probes needed"}


def compose(evidence):
    body = SOURCE.read_bytes().decode("utf-8")
    assert "\r" not in body, "soak_slots.lua.txt must be LF"
    assert body.count(MARKER) == 1, "probe sweep marker missing"
    lines = ["T.PreloadProbeSweep {\n"]
    for key in ("command", "output", "pack_head", "testkit_head", "checked_at", "brief"):
        literal = json.dumps(evidence[key]).replace("TEMPORARY", 'TEMP" .. "ORARY')
        lines.append(f"\t{key} = {literal},\n")
    lines.append(f"\texit = {int(evidence['exit'])}, hits = {{}}, needed = {{}},\n}}\n")
    header = ("-- SITTING: pre-launch train logistics SOAK (2026-10-03), slots 1-3; Scratch and 4-12 unbound.\n"
              "-- GENERATED by tools/trains/soak/compose.py in the Opt-In repo from soak_slots.lua.txt;\n"
              "-- edit that source and regenerate. Read-only stream: no fixture action, watch or\n"
              "-- trigger runs at load. Shipping Code/ is untouched.\n")
    return header + body.replace(MARKER, "".join(lines))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--install", action="store_true")
    args = parser.parse_args()
    evidence = sweep()
    if evidence["exit"] != 1 or evidence["output"] != "" or evidence["hits"]:
        raise SystemExit("probe sweep not clean: exit=%s hits=%s" % (evidence["exit"], evidence["hits"]))
    text = compose(evidence)
    OUTPUT.write_bytes(text.encode("utf-8"))
    receipt = {"source": str(SOURCE.relative_to(ROOT)).replace("\\", "/"),
               "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
               "output": str(OUTPUT.relative_to(ROOT)).replace("\\", "/"),
               "output_sha256": hashlib.sha256(OUTPUT.read_bytes()).hexdigest(),
               "sweep": evidence, "installed": None}
    if args.install:
        tasks = subprocess.check_output(["tasklist", "/FI", "IMAGENAME eq Mars.exe", "/FO", "CSV"], text=True)
        if '"Mars.exe"' in tasks:
            raise SystemExit("Mars.exe is running: close the game before installing the slots")
        shutil.copyfile(OUTPUT, TARGET)
        installed = hashlib.sha256(TARGET.read_bytes()).hexdigest()
        assert installed == receipt["output_sha256"]
        receipt["installed"] = {"path": str(TARGET), "sha256": installed,
                                "at": datetime.now(timezone.utc).isoformat()}
    RECEIPT.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"output": receipt["output"], "output_sha256": receipt["output_sha256"],
                      "sweep_exit": evidence["exit"], "sweep_output": evidence["output"],
                      "pack_head": evidence["pack_head"], "testkit_head": evidence["testkit_head"],
                      "installed": receipt["installed"]}, indent=2))
