-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========
-- First written by hand for brief 25 in the hub template's shape; the Mod Editor owns it after.

UndefineClass('SMROptInElevatorStationDev')
DefineClass.SMROptInElevatorStationDev = {
	__parents = { "Building" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 1,
	object_class = "Building",
	build_points = 1000,
	instant_build = true,
	is_tall = true,
	dome_forbidden = true,
	display_name = T(--[[ModItemBuildingTemplate SMROptInElevatorStationDev display_name]] "Elevator Station (look only)"),
	display_name_twolines = T(--[[ModItemBuildingTemplate SMROptInElevatorStationDev display_name_twolines]] "Elevator Station"),
	display_name_pl = T(--[[ModItemBuildingTemplate SMROptInElevatorStationDev display_name_pl]] "Elevator Stations (look only)"),
	description = T(--[[ModItemBuildingTemplate SMROptInElevatorStationDev description]] "DEV ONLY. The Elevator Station's look, for placing and viewing: a small train-hub dome with a store at its centre and a cargo-lift column, beside a rail with one connector at each end. It does nothing yet: no storage, no elevator range rule, no twin. Underground its column rises into the cave ceiling."),
	build_category = "Stations",
	display_icon = "UI/IconsRemaster/Buildings/elevator.png",
	build_pos = 20,
	entity = "SMROptInElevatorStation",
	label1 = "OutsideBuildings",
	disabled_in_environment = set( "Asteroid" ),
	persist_baseclass = "Building",
}

