-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('SMROptInElevatorDepotDev')
DefineClass.SMROptInElevatorDepotDev = {
	__parents = { "SMROptInElevatorDepotDevBase" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 2,
	object_class = "SMROptInElevatorDepotDevBase",
	build_points = 1000,
	instant_build = true,
	is_tall = true,
	dome_forbidden = true,
	use_demolished_state = true,
	display_name = T(--[[ModItemBuildingTemplate SMROptInElevatorDepotDev display_name]] "Elevator Depot (dev)"),
	display_name_twolines = T(--[[ModItemBuildingTemplate SMROptInElevatorDepotDev display_name_twolines]] "Elevator Depot"),
	display_name_pl = T(--[[ModItemBuildingTemplate SMROptInElevatorDepotDev display_name_pl]] "Elevator Depots (dev)"),
	description = T(--[[ModItemBuildingTemplate SMROptInElevatorDepotDev description]] "DEV ONLY. The Elevator Depot's look: a 75% space elevator with a tunnel mouth for trains. A working train station: connect a track to the mouth and trains drive in, stop inside and come back out. Its cabin runs for show only; no cargo crosses maps yet. Place it at least 100 m from other stations."),
	build_category = "Stations",
	display_icon = "UI/IconsRemaster/Buildings/elevator.png",
	build_pos = 20,
	entity = "SMROptInElevatorDepot",
	label1 = "OutsideBuildings",
	label2 = "OutsideBuildingsTargets",
	palette_color1 = "outside_TrainStation",
	disabled_in_environment = set( "Asteroid" ),
	electricity_consumption = 0,
	desire_slider_max = 60,
	desired_amount = 10000,
	persist_baseclass = "SMROptInElevatorDepotDevBase",
}

