-- ========== GENERATED BY GFXMaterial Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('GFXMaterial', {
	BaseColor = "B:\\Dev\\SMR\\SMR-Assets\\elevatorstation\\blender\\textures\\SMROptInElevatorStationGlass_BC.tga",
	BlendType = "blendGlass",
	CastContactShadow = false,
	CastShadow = false,
	DepthWrite = false,
	Normal = "B:\\Dev\\SMR\\SMR-Assets\\elevatorstation\\blender\\textures\\SMROptInElevatorStationGlass_NM.tga",
	RM = "B:\\Dev\\SMR\\SMR-Assets\\elevatorstation\\blender\\textures\\SMROptInElevatorStationGlass_RM.tga",
	ReceiveShadow = false,
	SI = "B:\\Dev\\SMR\\SMR-Assets\\elevatorstation\\blender\\textures\\SMROptInElevatorStationGlass_SI.tga",
	TwoSidedShading = true,
	id = "SMROptInElevatorStationGlass",
	mod_handle = 4,
	save_in = "Mod/SMR_ElevatorStationDev_20260929",
})

