-- ========== GENERATED BY GFXMaterial Editor DO NOT EDIT MANUALLY! ==========
-- First written by SMR-Assets/elevatorstation/blender/depot_paint.py (brief 28); the Mod Editor owns it after.

PlaceObj('GFXMaterial', {
	BaseColor = "B:\\Dev\\SMR\\SMR-Assets\\elevatorstation\\blender\\textures\\SMROptInElevatorDepot_BC.tga",
	Normal = "B:\\Dev\\SMR\\SMR-Assets\\elevatorstation\\blender\\textures\\SMROptInElevatorDepot_NM.tga",
	RM = "B:\\Dev\\SMR\\SMR-Assets\\elevatorstation\\blender\\textures\\SMROptInElevatorDepot_RM.tga",
	SI = "B:\\Dev\\SMR\\SMR-Assets\\elevatorstation\\blender\\textures\\SMROptInElevatorDepot_SI.tga",
	id = "SMROptInElevatorDepot",
	mod_handle = 6,
	save_in = "Mod/SMR_ElevatorStationDev_20260929",
})

