-- ========== GENERATED BY GFXMaterial Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('GFXMaterial', {
	BaseColor = "C:\\Dev\\SMR-TrainHubAssets\\blender\\textures\\TrainHub_BC.tga",
	Normal = "C:\\Dev\\SMR-TrainHubAssets\\blender\\textures\\TrainHub_NM.tga",
	RM = "C:\\Dev\\SMR-TrainHubAssets\\blender\\textures\\TrainHub_RM.tga",
	id = "SMROptInTrainHub6",
	mod_handle = 3,
	save_in = "Mod/SMR_TrainHubDev_20260918",
})

