-- ========== GENERATED BY GFXMaterial Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('GFXMaterial', {
	BaseColor = "C:\\Dev\\SMR-Assets\\trainhub\\blender\\textures\\concept\\SMROptInTrainHub6_BC.tga",
	Normal = "C:\\Dev\\SMR-Assets\\trainhub\\blender\\textures\\concept\\SMROptInTrainHub6_NM.tga",
	RM = "C:\\Dev\\SMR-Assets\\trainhub\\blender\\textures\\concept\\SMROptInTrainHub6_RM.tga",
	SI = "C:\\Dev\\SMR-Assets\\trainhub\\blender\\textures\\concept\\SMROptInTrainHub6_SI.tga",
	id = "SMROptInTrainHub6",
	mod_handle = 3,
	save_in = "Mod/SMR_TrainHubDev_20260918",
})

