-- ========== GENERATED BY GFXMaterial Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('GFXMaterial', {
	BaseColor = "B:\\Dev\\SMR\\SMR-Assets\\trainhub\\blender\\textures\\nostrips\\SMROptInTrainHub6_BC.tga",
	Normal = "B:\\Dev\\SMR\\SMR-Assets\\trainhub\\blender\\textures\\nostrips\\SMROptInTrainHub6_NM.tga",
	RM = "B:\\Dev\\SMR\\SMR-Assets\\trainhub\\blender\\textures\\nostrips\\SMROptInTrainHub6_RM.tga",
	SI = "B:\\Dev\\SMR\\SMR-Assets\\trainhub\\blender\\textures\\nostrips\\SMROptInTrainHub6_SI.tga",
	id = "SMROptInTrainHub6",
	mod_handle = 3,
	save_in = "Mod/SMR_TrainHubDev_20260918",
})

