-- ========== GENERATED BY GFXMaterial Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('GFXMaterial', {
	BaseColor = "B:\\Dev\\SMR\\SMR-Assets\\trainhub\\blender\\textures\\concept\\SMROptInTrainHub6Glass_BC.tga",
	BlendType = "blendGlass",
	CastContactShadow = false,
	CastShadow = false,
	DepthWrite = false,
	Normal = "B:\\Dev\\SMR\\SMR-Assets\\trainhub\\blender\\textures\\concept\\SMROptInTrainHub6Glass_NM.tga",
	RM = "B:\\Dev\\SMR\\SMR-Assets\\trainhub\\blender\\textures\\concept\\SMROptInTrainHub6Glass_RM.tga",
	ReceiveShadow = false,
	SI = "B:\\Dev\\SMR\\SMR-Assets\\trainhub\\blender\\textures\\concept\\SMROptInTrainHub6Glass_SI.tga",
	TwoSidedShading = true,
	id = "SMROptInTrainHub6Glass",
	mod_handle = 4,
	save_in = "Mod/SMR_TrainHubDev_20260918",
})

