-- ========== GENERATED BY SIE_ImportItem Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('SIE_ImportItem_Mesh', {
	Entity = "SMROptInTrainHub6",
	Mesh = "mesh",
	ScenePath = "C:/Dev/SMR-TrainHubAssets/blender/export/SMROptInTrainHub6.fbx",
	PlaceObj('SIE_ImportItemSelector', {
		'name', "RootNode",
	}, {
		PlaceObj('SIE_ImportItemSelector', {
			'name', "Origin",
			'UseAsOrigin', true,
		}, {
			PlaceObj('SIE_ImportItemSelector', {
				'name', "SMROptInTrainHub6",
				'ImportMesh', true,
				'Material', "SMROptInTrainHub6",
			}, {
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Box1",
					'SpotName', "Box1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Box1.001",
					'SpotName', "Box1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Box1.002",
					'SpotName', "Box1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Box1.003",
					'SpotName', "Box1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Box1.004",
					'SpotName', "Box1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Box1.005",
					'SpotName', "Box1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Top",
					'SpotName', "Top",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackconnector1",
					'SpotName', "Trackconnector1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackconnector2",
					'SpotName', "Trackconnector2",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackconnector3",
					'SpotName', "Trackconnector3",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackconnector4",
					'SpotName', "Trackconnector4",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackconnector5",
					'SpotName', "Trackconnector5",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackconnector6",
					'SpotName', "Trackconnector6",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackdirection1",
					'SpotName', "Trackdirection1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackdirection2",
					'SpotName', "Trackdirection2",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackdirection3",
					'SpotName', "Trackdirection3",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackdirection4",
					'SpotName', "Trackdirection4",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackdirection5",
					'SpotName', "Trackdirection5",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackdirection6",
					'SpotName', "Trackdirection6",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-WorkDrone",
					'SpotName', "WorkDrone",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-WorkDrone.001",
					'SpotName', "WorkDrone",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-WorkDrone.002",
					'SpotName', "WorkDrone",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-WorkDrone.003",
					'SpotName', "WorkDrone",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-WorkDrone.004",
					'SpotName', "WorkDrone",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-WorkDrone.005",
					'SpotName', "WorkDrone",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "Collision",
					'SurfaceType', "collision",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "hex_shape",
					'SurfaceType', "hex_shape",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "Selection",
					'SurfaceType', "selection",
				}),
				}),
			}),
		}),
})

