-- ========== GENERATED BY SIE_ImportItem Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('SIE_ImportItem_Mesh', {
	Entity = "SMROptInElevatorDepot",
	Mesh = "mesh",
	ScenePath = "B:/Dev/SMR/SMR-Assets/elevatorstation/blender/export/SMROptInElevatorDepot.fbx",
	PlaceObj('SIE_ImportItemSelector', {
		'name', "RootNode",
	}, {
		PlaceObj('SIE_ImportItemSelector', {
			'name', "Origin",
			'UseAsOrigin', true,
		}, {
			PlaceObj('SIE_ImportItemSelector', {
				'name', "SMROptInElevatorDepot",
				'ImportMesh', true,
				'Material', "SMROptInElevatorStation",
			}, {
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackconnector1",
					'SpotName', "Trackconnector1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackdirection1",
					'SpotName', "Trackdirection1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackconnector2",
					'SpotName', "Trackconnector2",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Trackdirection2",
					'SpotName', "Trackdirection2",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Ramparrive1",
					'SpotName', "Ramparrive1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Stop1",
					'SpotName', "Stop1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Spawn2",
					'SpotName', "Spawn2",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Spawn1",
					'SpotName', "Spawn1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Stop2",
					'SpotName', "Stop2",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Rampdepart1",
					'SpotName', "Rampdepart1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Ramparrive2",
					'SpotName', "Ramparrive2",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Rampdepart2",
					'SpotName', "Rampdepart2",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "-Sign1",
					'SpotName', "Sign1",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "hex_shape",
					'SurfaceType', "hex_shape",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "Selection",
					'SurfaceType', "selection",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "Collision",
					'SurfaceType', "collision",
				}),
				PlaceObj('SIE_ImportItemSelector', {
					'name', "terrain_hole",
					'SurfaceType', "terrain_hole",
				}),
				}),
			}),
		}),
})

