-- ========== GENERATED BY SIE_ImportItem Editor DO NOT EDIT MANUALLY! ==========
-- First written by SMR-Assets/elevatorstation/blender/station_build.py; the Mod Editor owns it after.

PlaceObj('SIE_ImportItem_Mesh', {
	Entity = "SMROptInElevatorStationGlass",
	Mesh = "mesh",
	ScenePath = "B:/Dev/SMR/SMR-Assets/elevatorstation/blender/export/SMROptInElevatorStationGlass.fbx",
	PlaceObj('SIE_ImportItemSelector', {
		'name', "RootNode",
	}, {
		PlaceObj('SIE_ImportItemSelector', {
			'name', "Origin",
			'UseAsOrigin', true,
		}, {
			PlaceObj('SIE_ImportItemSelector', {
				'name', "SMROptInElevatorStationGlass",
				'ImportMesh', true,
				'Material', "SMROptInElevatorStationGlass",
			}),
			}),
		}),
})
