-- ========== GENERATED BY SIE_ImportItem Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('SIE_ImportItem_Mesh', {
	Entity = "SMROptInElevatorDepotReceiver",
	Mesh = "mesh",
	ScenePath = "B:/Dev/SMR/SMR-Assets/elevatorstation/blender/export/SMROptInElevatorDepotReceiver.fbx",
	PlaceObj('SIE_ImportItemSelector', {
		'name', "RootNode",
	}, {
		PlaceObj('SIE_ImportItemSelector', {
			'name', "ReceiverOrigin",
			'UseAsOrigin', true,
		}, {
			PlaceObj('SIE_ImportItemSelector', {
				'name', "SMROptInElevatorDepotReceiver",
				'ImportMesh', true,
				'Material', "SMROptInElevatorStation",
			}),
			}),
		}),
})

