-- ========== GENERATED BY EntitySpec Editor (Ctrl-Alt-A) DO NOT EDIT MANUALLY! ==========

if Platform.ged then return end
EntityData["SMROptInElevatorDepot"] = {
	collision_meshes = "open",
	editor_artset = "Mods",
	editor_category = "Common",
	editor_subcategory = "Common",
	entity = {
		class_parent = "BuildingEntityClass",
	},
}
EntityData["SMROptInElevatorDepotReceiver"] = {
	editor_artset = "Mods",
	editor_category = "Buildings",
	editor_subcategory = "Common",
}
