-- ========== GENERATED BY SIE_ImportItem Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('SIE_ImportItem_Mesh', {
	Entity = "SMROptInTrainHub6Glass",
	Mesh = "mesh",
	ScenePath = "B:/Dev/SMR/SMR-Assets/trainhub/blender/export/concept/SMROptInTrainHub6Glass.fbx",
	PlaceObj('SIE_ImportItemSelector', {
		'name', "RootNode",
	}, {
		PlaceObj('SIE_ImportItemSelector', {
			'name', "Origin",
			'UseAsOrigin', true,
		}, {
			PlaceObj('SIE_ImportItemSelector', {
				'name', "SMROptInTrainHub6Glass",
				'ImportMesh', true,
				'Material', "SMROptInTrainHub6Glass",
			}),
			}),
		}),
})

