-- ========== GENERATED BY EntitySpec Editor (Ctrl-Alt-A) DO NOT EDIT MANUALLY! ==========

if Platform.ged then return end
PlaceObj('EntitySpec', {
	class_parent = "BuildingEntityClass",
	id = "SMROptInElevatorDepot",
	last_change_time = 1790756375,
	mod_handle = 1,
	save_in = "Mod/SMR_ElevatorStationDev_20260929",
})

