-- ========== GENERATED BY EntitySpec Editor (Ctrl-Alt-A) DO NOT EDIT MANUALLY! ==========

if Platform.ged then return end
PlaceObj('EntitySpec', {
	class_parent = "BuildingEntityClass",
	editor_category = "Buildings",
	id = "SMROptInTrainHub6",
	last_change_time = 1789817428,
	mod_handle = 2,
	save_in = "Mod/SMR_TrainHubDev_20260918",
})

PlaceObj('EntitySpec', {
	id = "SMROptInTrainHub6Glass",
	last_change_time = 1790140860,
	mod_handle = 5,
	save_in = "Mod/SMR_TrainHubDev_20260918",
})

