-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('SMROptInTrainHub6')
DefineClass.SMROptInTrainHub6 = {
	__parents = { "SMROptInTrainHub6Base" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 1,
	object_class = "SMROptInTrainHub6Base",
	construction_cost_Concrete = 50000,
	construction_cost_Metals = 30000,
	construction_cost_MachineParts = 10000,
	build_points = 5000,
	is_tall = true,
	dome_forbidden = true,
	use_demolished_state = true,
	can_refab = false,
	maintenance_resource_type = "Metals",
	maintenance_resource_amount = 5000,
	display_name = T(909018002001, --[[ModItemBuildingTemplate SMROptInTrainHub6 display_name]] "Train Hub"),
	display_name_twolines = T(909018002002, --[[ModItemBuildingTemplate SMROptInTrainHub6 display_name_twolines]] "Train Hub"),
	display_name_pl = T(909018002003, --[[ModItemBuildingTemplate SMROptInTrainHub6 display_name_pl]] "Train Hubs"),
	description = T(909018002004, --[[ModItemBuildingTemplate SMROptInTrainHub6 description]] "A <em>Station</em> where three straight lines cross, so cargo can change routes. It has its own small <em>Drone</em> crew and keeps back enough Metals to maintain itself."),
	build_category = "Stations",
	display_icon = "UI/IconsRemaster/Buildings/large_train_station.png",
	build_pos = 19,
	entity = "TrainStationLargeCCP3",
	label1 = "OutsideBuildings",
	label2 = "OutsideBuildingsTargets",
	palette_color1 = "outside_TrainStation",
	demolish_sinking = range(5, 15),
	demolish_tilt_angle = range(900, 1500),
	demolish_debris = 85,
	disabled_in_environment = set( "Asteroid" ),
	electricity_consumption = 10000,
	desire_slider_max = 120,
	desired_amount = 10000,
	max_storage_per_resource = 240000,
	persist_baseclass = "SMROptInTrainHub6Base",
}

